# Generated by Django 3.0.8 on 2022-01-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_neighbourhood_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='name',
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='neighbourHood_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
